export const API_TIMEOUT_MS = 30000;
export const CHARACTER_LIMIT = 25000;

export {
  ALL_LEAGUES,
  LEADERBOARD_LEAGUES,
  TEAM_STATS_LEAGUES,
  TEAM_ROSTER_LEAGUES,
  AGGREGATE_SCOPES,
} from './leagues.js';
